FROM node:22-alpine AS deps

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev


FROM node:22-alpine

RUN apk add --no-cache \
    tzdata \
    texlive \
    texmf-dist-latexextra \
    texmf-dist-fontsextra

WORKDIR /app

COPY --from=deps --chown=node:node /app/node_modules ./node_modules
COPY --chown=node:node . .

EXPOSE 8080

USER node

CMD ["npm", "start"]